### ISSUE TITLE
Exception class not defined

### ISSUE THREAD

**Issue by slackmart** [level12/py3270#4]
Even though the emulator reaches `emulator.terminate()` statement, the `BrokenPipeError` is thrown, the traceback is the following:
```
      except BrokenPipeError:   # noqa
NameError: global name 'BrokenPipeError' is not defined
Exception NameError: "global name 'BrokenPipeError' is not defined" in <bound method Emulator.__del__ of <py3270.Emulator object at 0x000000000000028394>> ignored
```
By inspecting the code, I found the named exception effectively has not been defined.

**Comment by rsyring** [comment]
Note that this is a problem only in Python 2.7 as `BrokenPipeError` is not available until Python 3.
